site_name: Muthupandian
site_author: Muthu
copyright: "Copyright &copy; 2022 Muthupandian Thangarajan"
site_url: https://muthupandian.in

# Repository
repo_name: muthugit/muthugit.github.io
repo_url: https://github.com/muthugit/muthugit.github.io
edit_uri: ""

plugins:
  - git-revision-date-localized
  - blogging:
      features:
        tags: {}
      dirs: # The directories to be included
        - blog
        # - pyBook

      categories:
        # {{ blog_content pyBook }}
        - name: pyBook
          sort: 
            from: old
            by: creation 
          show_total: true
          # theme:             # Use a predefined theme
          #   name: card
          dirs:
            - pyBook/OOPs
            - pyBook/Tips
        - name: thoughts
          sort:
            from: new
          show_total: true
          dirs: 
            - thoughts

theme:
  font:
    text: Roboto
  # palette:
  #   primary: black
  name: material
  custom_dir: docs/overrides
  palette:
    primary: black
    accent: grey
  features:
    - tabs
    # - navigation.instant
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.indexes 
    - navigation.path
    - navigation.sections
    - navigation.expand
    - navigation.top
    - toc.integrate
    - navigation.footer
    # - header.autohide
  feature:
    tabs: true
extra_css:
  - doc.css
  # - dark-theme.css
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.css
extra_javascript:
  - https://unpkg.com/mermaid@7.1.2/dist/mermaid.min.js
google_analytics: ['UA-60832787-1', 'muthupandian.in']
extra:
  analytics:
    provider: google
    property: G-H1XE5TWYYB
    # property: UA-60832787-1
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_div_format
  #     emoji_index: !!python/name:materialx.emoji.twemoji
  #     emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  # - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde